[package]
name = "elapsed"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"

[dependencies.tasklib]
git = "https://github.com/AceofSpades5757/tasklib-rs"
branch = "update"
